### ISSUE TITLE
Progress Reporting

### ISSUE THREAD

**Issue by mjpt777** [melix/jmh-gradle-plugin#45] opened 2015-11-24 17:14 UTC
It would be great if the plugin reported progress of the JMH benchmark that is executing. In the current form it is stuck at 88% and appears like the build is broken to a newbie.

**Comment by vyazelenko** [comment] 2015-12-01 23:00
Duplicate of #17. Can be closed once pull #33 is merged.

**Comment by vyazelenko** [comment] 2015-12-01 23:15
Actually #33 was already merged but issue #17 was not closed.

**Closed** 2015-12-02 17:36 UTC
