### ISSUE TITLE
append method not found for jmhJar

### ISSUE THREAD

**Issue by gAmUssA** [melix/jmh-gradle-plugin#50] opened 2016-01-07 04:00 UTC
Shadow Plugin doesn't work

```
jmhJar {
    append 'META-INF/services/com.hazelcast.client.ClientExtension'
}
```

```
$ ./gradlew jmhJar

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/apple/projects/build.gradle' line: 119

* What went wrong:
A problem occurred evaluating root project 'Benchmark Suite'.
> Could not find method append() for arguments [META-INF/services/com.hazelcast.client.ClientExtension] on root project 'Benchmark Suite'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.302 secs
```

**Comment by gAmUssA** [comment] 2016-01-07 04:13
I think this is somehow related to https://github.com/melix/jmh-gradle-plugin/issues/38
Just switched to `buildScript` syntax and shadow plugin work

**Comment by vyazelenko** [comment] 2016-01-21 22:56
Duplicate of #38

**Comment by vyazelenko** [comment] 2016-02-24 17:53
As long as Shadow plugin applied first everything works as expected.

**Comment by aalmiray** [comment] 2016-02-24 18:07
exactly. I think we can leave this issue as it is now as I believe Gradle will change how configuration is executed in its next big release.

**Closed by aalmiray** 2016-02-24 18:07 UTC
